sample_questions: list[dict[str, str | list[str]]] = [
    {
        "question_id": "Q0001",
        "question": "What is the capital of France?",
        "options": ["Berlin", "Madrid", "Paris", "Rome"],
        "answer": "Paris",
    },
    {
        "question_id": "Q0002",
        "question": "Which planet is known as the Red Planet?",
        "options": ["Earth", "Jupiter", "Mars", "Venus"],
        "answer": "Mars",
    },
    {
        "question_id": "Q0003",
        "question": "Who wrote 'To Kill a Mockingbird'?",
        "options": ["J.K. Rowling", "Harper Lee", "Ernest Hemingway", "Mark Twain"],
        "answer": "Harper Lee",
    },
    {
        "question_id": "Q0004",
        "question": "What is the largest mammal in the world?",
        "options": ["Elephant", "Blue Whale", "Giraffe", "Orca"],
        "answer": "Blue Whale",
    },
    {
        "question_id": "Q0005",
        "question": "Who painted the Mona Lisa?",
        "options": ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"],
        "answer": "Leonardo da Vinci",
    },
    {
        "question_id": "Q0006",
        "question": "What is the chemical symbol for gold?",
        "options": ["Au", "Ag", "Pb", "Hg"],
        "answer": "Au",
    },
    {
        "question_id": "Q0007",
        "question": "What is the longest river in the world?",
        "options": ["Amazon River", "Nile River", "Mississippi River", "Yangtze River"],
        "answer": "Nile River",
    },
    {
        "question_id": "Q0008",
        "question": "Who is the author of the Harry Potter series?",
        "options": ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "C.S. Lewis"],
        "answer": "J.K. Rowling",
    },
    {
        "question_id": "Q0009",
        "question": "What is the smallest prime number?",
        "options": ["0", "1", "2", "3"],
        "answer": "2",
    },
    {
        "question_id": "Q0010",
        "question": "In which year did the Titanic sink?",
        "options": ["1905", "1912", "1918", "1925"],
        "answer": "1912",
    },
    {
        "question_id": "Q0011",
        "question": "What is the currency of Japan?",
        "options": ["Yen", "Dollar", "Euro", "Won"],
        "answer": "Yen",
    },
    {
        "question_id": "Q0012",
        "question": "Which gas is most abundant in the Earth's atmosphere?",
        "options": ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide"],
        "answer": "Nitrogen",
    },
    {
        "question_id": "Q0013",
        "question": "Who developed the theory of relativity?",
        "options": ["Isaac Newton", "Galileo Galilei", "Nikola Tesla", "Albert Einstein"],
        "answer": "Albert Einstein",
    },
    {
        "question_id": "Q0014",
        "question": "What is the hardest natural substance on Earth?",
        "options": ["Gold", "Iron", "Diamond", "Platinum"],
        "answer": "Diamond",
    },
    {
        "question_id": "Q0015",
        "question": "Which element has the chemical symbol 'O'?",
        "options": ["Gold", "Oxygen", "Osmium", "Oganesson"],
        "answer": "Oxygen",
    },
    {
        "question_id": "Q0016",
        "question": "What is the capital city of Australia?",
        "options": ["Sydney", "Melbourne", "Canberra", "Perth"],
        "answer": "Canberra",
    },
    {
        "question_id": "Q0017",
        "question": "Which planet is closest to the sun?",
        "options": ["Venus", "Earth", "Mercury", "Mars"],
        "answer": "Mercury",
    },
    {
        "question_id": "Q0018",
        "question": "What is the main ingredient in guacamole?",
        "options": ["Tomato", "Onion", "Avocado", "Pepper"],
        "answer": "Avocado",
    },
    {
        "question_id": "Q0019",
        "question": "Which ocean is the largest?",
        "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
        "answer": "Pacific Ocean",
    },
    {
        "question_id": "Q0020",
        "question": "What is the square root of 64?",
        "options": ["6", "7", "8", "9"],
        "answer": "8",
    },
    {
        "question_id": "Q0021",
        "question": "Who discovered penicillin?",
        "options": ["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Joseph Lister"],
        "answer": "Alexander Fleming",
    },
    {
        "question_id": "Q0022",
        "question": "What is the largest planet in our solar system?",
        "options": ["Earth", "Saturn", "Jupiter", "Neptune"],
        "answer": "Jupiter",
    },
    {
        "question_id": "Q0023",
        "question": "Which country is known as the Land of the Rising Sun?",
        "options": ["China", "Japan", "South Korea", "Thailand"],
        "answer": "Japan",
    },
    {
        "question_id": "Q0024",
        "question": "What is the most spoken language in the world?",
        "options": ["Spanish", "English", "Mandarin Chinese", "Hindi"],
        "answer": "Mandarin Chinese",
    },
    {
        "question_id": "Q0025",
        "question": "Who wrote the play 'Romeo and Juliet'?",
        "options": ["Christopher Marlowe", "Ben Jonson", "William Shakespeare", "John Webster"],
        "answer": "William Shakespeare",
    },
    {
        "question_id": "Q0026",
        "question": "Which continent is the Sahara Desert located on?",
        "options": ["Asia", "South America", "Africa", "Australia"],
        "answer": "Africa",
    },
    {
        "question_id": "Q0027",
        "question": "What is the largest bone in the human body?",
        "options": ["Femur", "Tibia", "Humerus", "Radius"],
        "answer": "Femur",
    },
    {
        "question_id": "Q0028",
        "question": "What is the chemical formula for water?",
        "options": ["H2O", "CO2", "O2", "H2"],
        "answer": "H2O",
    },
    {
        "question_id": "Q0029",
        "question": "Which country gifted the Statue of Liberty to the United States?",
        "options": ["United Kingdom", "France", "Spain", "Germany"],
        "answer": "France",
    },
    {
        "question_id": "Q0030",
        "question": "Who is known as the Father of Computers?",
        "options": ["Charles Babbage", "Alan Turing", "John von Neumann", "Steve Jobs"],
        "answer": "Charles Babbage",
    },
]
